//
//  AccessibityKey.swift
//  WeatherToday
//
//  Created by Alaattin Bedir on 15.06.2022.
//

import Foundation

enum AccessibilityKey: String {
    case title
    case date
    case cardAccountPickerTitle
    case pageInfo
    case stepNumber
    case back
    case settings
    case close
    case continueButton
    case clearButton
    case custom
    case logo
    case header
    case username
    case password
    case passwordAgain
    case otp
    case otpCountDown
    case sendAgain
    case cardName
    case cardNo
    case cvv
    case cvvTitle
    case cvvInfo
    case animation
    case name
    case limitTitle
    case limit
    case limitPercentage
    case bonusTitle
    case bonus
    case bonusPercentage
    case favoriteButton
    case favoriteLabel
    case error
    case barLogo
    case barTitle
    case alertTitle
    case alertMessage
    case alertIcon
    case amount
    case amountTitle
    case totalAmount
    case totalAmountTitle
    case installmentTitle
    case welcome
    case internet
    case internetToggle
    case phone
    case phoneToggle
    case abroad
    case abroadToggle
    case pin
    case pinRepeat
    case label
    case label1
    case label2
    case label3
    case label4
    case label5
    case labelConditionsTitle
    case labelConditions
    case image1
    case image2
    case image3
    case image4
    case description
    case search
    case declaredIncomeAmount
    case requestedLimitAmount
    case subTitle
    case email
    case buttonShowMore
    case delete
    case cardPickerObjectTitle
    case cardPickerObjectDetail1
    case cardPickerObjectDetail2
    case cardPickerAmount
    case cardPickerbalance
    case cardPickerButtonSelection
    case number
    case branch
    case pairKey
    case pairValue
    case checkbox
    case statementTitle
    case statementSelectionTitle
    case statementSelectionView
    case pickerDetail
    case statement
    case pickerTitle
    case pickerError
    case totalLimitTitle
    case totalLimit
    case totalLimitViewTitle
    case cardDetailView
    case countText
    case button1
    case button2
    case button3
    case cardAccountPickerImage
    case cardAccountPickerActiveImage
    case selected
    case unSelected
    case address
    case popupTitle
    case popupDescription
    case textField
    case textField1
    case textField2
    case textField3
    case textField4
    case textField5
    case textField6
    case profileImage
    case forgotPassword
    case btnNotMe
    case showHide
    case labelLeft1
    case labelLeft2
    case labelLeft3
    case labelLeft4
    case labelLeft5
    case labelLeft6
    case labelRight1
    case labelRight2
    case labelRight3
    case labelRight4
    case labelRight5
    case labelRight6
    case labelMiddle1
    case labelMiddle2
    case labelMiddle3
    case message
    case tckn
    case tcknValue
    case fullName
    case fullNameValue
    case tax
    case taxValue
    case identityType
    case identityValue
    case identityNo
    case identityNoValue
    case team
    case pfTeam
    case intTeam
    case pfIntTeam
    case viewInfoAlert
    case switchButton
    case switchButton1
    case labelCategory
    case labelTag
    case buttonMenu
    case progresView
    case pay
    case statementAmountTitle
    case statementAmount
    case minimumPaymentTitle
    case minimumPayment
    case imgSelect
    case viewMain
    case viewInfo
    case transactionCountTitle
    case transactionCount
    case totalPaybackAmountTitle
    case totalPaybackAmount
    case statementAmountViewTitle
    case statementDate
    case futureStatementView
    case futureStatementInfo
    case cardPickerView
    case scrollView
    case viewFutureStatementInfo
    case viewStatementAmount
    case info
    case tableView
    case fragmentName
    case fragmentAmount
    case fragmentCount
    case fragmentDate
    case fragmentInfo
    case maximumFragmentCount
    case totalAmountValue
    case fragmentCountValue
    case maximumFragmentCountValue
    case fragmentNo
    case operationCount
    case installmentOperation
    case fragmentTableView
    case informationText
    case buttonApprove
    case actionsStackView
    case lastPaymentValue
    case fragmentDateTitle
    case lastPaymentTitle
    case labelInfo
    case pickerFormField1
    case pickerFormField2
    case commitmentCampaignTitle
    case commitmentCampaignAmount
    case commitmentMonthlyAmountTitle
    case commitmentMonthlyAmount
    case commitmentPeriodCountTitle
    case commitmentPeriodCount
    case campaignPrizeTitle
    case campaignPrize
    case cardInfo
    case commitmentStartDate
    case commitmentStartDateTitle
    case commitmentEndDate
    case commitmentDescriptionFollow
    case commitmentPeriodPayment
    case commitmentNecessaryPayment
    case commitmentNecessaryPaymentTitle
    case commitmentPeriodPaymentTitle
    case commitmentRemainingPeriodCount
    case commitmentRemainingPeriodCountTitle
    case commitmentStatus
    case commitmentStatusTitle
    case commitmentEndDateTitle
    case commitmentPreviousPeriodPaymentTitle
    case commitmentDefineDate
    case commitmentDefineDateTitle
    case commitmentPreviousPeriodPayment
    case imageArrow
    case commitmentInformation
    case commitmentBack
    case commitmentViewTitle
    case warning
    case laterButton
    case viewStatements
    case openNewPageView
    case labelTitle
    case remainingTitle
    case getButton
    case generateButton
    case copyButton
    case seeDetail
    case cardImage
    case cardApplicationTrackingStatus
    case progress
    case earnedBonusTitle
    case earnedBonus
    case earnedBonusPercentage
    case campaignRewardsTitle
    case campaignRewards
    case campaignRewardsPercentage
    case spendingRewardsTitle
    case spendingRewards
    case spendingRewardsPercentage
    case closableCardImageView
    case lblNew
    case inboxDateError
    var value: String {
        return rawValue
    }
}
